config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "dashboard", to: "pages#dashboard", as: :dashboard

  resources :processos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/controle.rb
class Controle < ApplicationRecord
  belongs_to :processo
  belongs_to :risco
  has_many :planos, dependent: :destroy

  validates :nome, presence: true
end

app/models/plano.rb
class Plano < ApplicationRecord
  belongs_to :controle
end

app/models/processo.rb
class Processo < ApplicationRecord
  has_many :riscos, dependent: :destroy
  has_many :controles, dependent: :destroy
  has_many :planos, dependent: :destroy

  validates :nome, presence: true
  validates :orgao1, presence: true
end

app/models/risco.rb
class Risco < ApplicationRecord
  belongs_to :processo
  has_many :controles, dependent: :destroy
  has_many :planos, dependent: :destroy

  validates :nome, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          authentication_keys: [:matricula] # Usando a matricula como login
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/controles_controller.rb
class ControlesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @user = User.new
  end
end

app/controllers/planos_controller.rb
class PlanosController < ApplicationController
end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController
  before_action :set_processo, only: [:show, :edit, :update, :destroy]

  def index
    @processos = Processo.all
  end

  def show
  end

  def new
    @processo = Processo.new
  end

  def create
    @processo = Processo.new(processo_params)
    if @processo.save
      redirect_to processos_url, notice: "Processo criado com sucesso!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @processo = Processo.find(params[:id])
    if @processo.update(processo_params)
      redirect_to processos_url, notice: "Processo atualizado com sucesso!"
    else
      render 'edit'
    end
  end

  def destroy
    @processo.destroy
    redirect_to processos_url, notice: "Processo excluído com sucesso!"
  end

  private

  def processo_params
    params.require(:processo).permit(:nome, :orgao1, :orgao2, :gestor_processo_1, :gestor_processo_2,
                                     :servidor_responsavel, :objetivo_estrategico_associado, :embasamento_legal,
                                     :sistemas_utilizados, :partes_interessadas)
  end

  def set_processo
    @processo = Processo.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_in_path_for(resource)
    processos_path(resource)
  end

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :matricula)
  end
end

app/controllers/riscos_controller.rb
class RiscosController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    processos_path(resource)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riscos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<%# <div>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href=<%= render 'processos/index' %><%#Processos</a>
    <%# </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Riscos</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Controles</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Planos de Ação</a>
    </li>
  </ul>
</div> %>

app/views/pages/home.html.erb
<div class="container d-flex border shadow p-3 mt-5" style="width: 1200px;">
  <div class="container">
    <h3 class="p-2">Bem-vindo ao Sistema de Controles de Riscos da Controladoria-Geral do Município do Rio de Janeiro</h3>
    <p>Este sistema foi construído com o propósito de conhecer mais dos processos de trabalho de cada setor da CGM-RIO e dirimir os possíveis riscos atrelados a cada processo de trabalho.</p>
  </div>

  <div class="container d-flex justify-content-center p-2">
    <%= simple_form_for(@user, url: session_path(@user)) do |f| %>
      <div class="form-inputs">
        <%= f.input :matricula,
                    required: false,
                    autofocus: true,
                    input_html: { autocomplete: "matricula" },
                    label: false,
                    placeholder: "Matrícula" %>
        <%= f.input :password,
                    required: false,
                    input_html: { autocomplete: "current-password" },
                    label: false,
                    placeholder: "Senha" %>
        <%= f.input :remember_me, as: :boolean, label: "Lembrar-me" %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Login", class: "btn btn-primary" %>
      </div>
      <p class="my-3"><%= link_to "Primeiro acesso? Cadastre-se!", new_user_registration_path %></p>
    <% end %>
  </div>
</div>

app/views/processos/_form.html.erb
<div class="container my-5">
    <%= simple_form_for @processo do |f| %>
      <%= f.input :nome, label: 'Nome do Processo:' %>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :orgao1, label: 'Órgão Responsável 1:' %>
        </div>
        <div class="col-md-6">
          <%= f.input :orgao2, label: 'Órgão Responsável 2:' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :gestor_processo_1, label: 'Gestor Responsável 1:' %>
        </div>
        <div class="col-md-6">
          <%= f.input :gestor_processo_2, label: 'Gestor Responsável 2:' %>
        </div>
      </div>
      <%= f.input :servidor_responsavel, label: 'Servidor Responsável:' %>
      <%= f.input :objetivo_estrategico_associado, label: 'Objetivo Estratégico Associado:' %>
      <%= f.input :embasamento_legal, label: 'Embasamento Legal:' %>
      <%= f.input :sistemas_utilizados, label: 'Sistemas Utilizados:' %>
      <%= f.input :partes_interessadas, label: 'Partes Interessadas:' %>
      
      <% if @processo.new_record? %>
        <%= f.button :submit, "Cadastrar", class: "btn btn-primary" %>
      <% else %>
        <%= f.button :submit, "Atualizar", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>

app/views/processos/edit.html.erb
<div class="container">
  <h2 class="d-flex justify-content-center">Edite o processo cadastrado</h2>
  <%= render "form", processo: @processo %>
</div>

app/views/processos/index.html.erb
<div class="container my-4">
  <div class="d-flex flex-row-reverse">
    <%= button_to raw("<i class='fa-solid fa-plus'></i>"), new_processo_path, method: :get, style: "width: 70px; cursor: pointer;", class: "btn btn-outline-secondary rounded-pill" %>
  </div>
  <% if @processos.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Orgão 1</th>
          <th>Orgão 2</th>
          <th>Gestor Processo 1</th>
          <th>Gestor Processo 2</th>
          <th>Servidor Responsável</th>
          <th>Objetivo Estratégico Associado</th>
          <th>Embasamento Legal</th>
          <th>Sistemas Utilizados</th>
          <th>Partes Interessadas</th>
        </tr>
      </thead>
      <tbody>
        <% @processos.each do |processo| %>
          <tr>
            <td><%= processo.nome %></td>
            <td><%= processo.orgao1 %></td>
            <td><%= processo.orgao2 %></td>
            <td><%= processo.gestor_processo_1 %></td>
            <td><%= processo.gestor_processo_2 %></td>
            <td><%= processo.servidor_responsavel %></td>
            <td><%= processo.objetivo_estrategico_associado %></td>
            <td><%= processo.embasamento_legal %></td>
            <td><%= processo.sistemas_utilizados %></td>
            <td><%= processo.partes_interessadas %></td>
            <td><%= link_to raw('<i class="fa-solid fa-pen"></i>'), edit_processo_path(processo) %></td>
            <td><%= link_to raw('<i class="fa-solid fa-trash-can"></i>'), processo_path(processo), data: {turbo_method: :delete, turbo_confirm: 'Você tem certeza?'}, class:"delete" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="row">
      <div class="col-md-12">
        <h2>Nenhum processo cadastrado</h2>
      </div>
    </div>
  <% end %>
</div>

app/views/processos/new.html.erb
<div class="container p-5">
  <h2 class="d-flex justify-content-center">Cadastro de novo processo</h2>
  <%= render "form", processo: @processo%>
</div>

app/views/processos/show.html.erb
<div class="container my-4">
  <p><strong>Nome: </strong><%= @processo.nome %></p>
  <p><strong>Órgão 1: </strong><%= @processo.orgao1 %></p>
  <p><strong>Órgão 2: </strong><%= @processo.orgao2 %></p>
  <p><strong>Gestor do Processo 1: </strong><%= @processo.gestor_processo_1 %></p>
  <p><strong>Gestor do Processo 2: </strong><%= @processo.gestor_processo_2 %></p>
  <p><strong>Servidor Responsável: </strong><%= @processo.servidor_responsavel %></p>
  <p><strong>Objetivo Estratégico Associado: </strong><%= @processo.objetivo_estrategico_associado %></p>
  <p><strong>Embasamento Legal: </strong><%= @processo.embasamento_legal %></p>
  <p><strong>Sistemas Utilizados: </strong><%= @processo.sistemas_utilizados %></p>
  <p><strong>Partes Interessadas: </strong><%= @processo.partes_interessadas %></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>